# Generated by Django 5.0.4 on 2025-11-04 16:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="s3_prefix",
            field=models.CharField(
                blank=True,
                help_text="S3 folder path for event files",
                max_length=500,
                verbose_name="S3 Prefix",
            ),
        ),
    ]
