# Generated by Django 5.0.4 on 2024-07-01 15:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_event_attendees_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bucket_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
