# Generated by Django 5.0.4 on 2026-02-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


def backfill_event_owner(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    EventParticipant = apps.get_model('events', 'EventParticipant')
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(auth_app_label, auth_model_name)

    event_ids = list(Event.objects.filter(user_id__isnull=True).values_list('id', flat=True))
    if not event_ids:
        return

    fallback_user_id = UserModel.objects.order_by('id').values_list('id', flat=True).first()
    if fallback_user_id is None:
        msg = 'Cannot backfill events_event.user_id because no users exist in the database.'
        raise RuntimeError(msg)

    for event_id in event_ids:
        owner_user_id = (
            EventParticipant.objects.filter(event_id=event_id, role='OWNER').order_by('id').values_list('user_id', flat=True).first()
        )
        if owner_user_id is None:
            owner_user_id = (
                EventParticipant.objects.filter(event_id=event_id).order_by('id').values_list('user_id', flat=True).first()
            )

        Event.objects.filter(id=event_id).update(user_id=owner_user_id or fallback_user_id)

    remaining = Event.objects.filter(user_id__isnull=True).count()
    if remaining:
        msg = f'Backfill failed: {remaining} events still have null owner.'
        raise RuntimeError(msg)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_inviteeventlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_events',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Event Owner',
            ),
        ),
        migrations.RunPython(backfill_event_owner, noop_reverse),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(
                db_index=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_events',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Event Owner',
            ),
        ),
    ]
