# Generated by Django 5.0.4 on 2024-10-28 17:08

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_event_event_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_prefix',
        ),
        migrations.AddField(
            model_name='event',
            name='event_gallery_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('dietary_preferences', models.TextField(blank=True)),
                (
                    'rsvp_status',
                    models.CharField(
                        choices=[
                            ('accepted', 'Accepted'),
                            ('declined', 'Declined'),
                            ('pending', 'Pending'),
                            ('tentative', 'Tentative'),
                            ('canceled', 'Canceled'),
                            ('no_show', 'No Show'),
                            ('waitlisted', 'Waitlisted'),
                            ('maybe', 'Maybe'),
                            ('confirmed_plus_one', 'Confirmed Plus One'),
                            ('declined_with_regret', 'Declined with Regret'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
