# Generated by Django 5.0.4 on 2024-11-12 19:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_remove_event_attendees_remove_event_bucket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_gallery_url',
            field=models.CharField(editable=False, unique=True),
        ),
    ]
