# Generated by Django 5.0.4 on 2026-02-24 21:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_readd_event_user_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteeventlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invite Event Link', 'verbose_name_plural': 'Invite Event Links'},
        ),
        migrations.AddField(
            model_name='inviteeventlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inviteeventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='inviteeventlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this invitation link expires', null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='inviteeventlink',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique token for invitation link', unique=True, verbose_name='Invite Token'),
        ),
        migrations.AlterField(
            model_name='inviteeventlink',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times this link can be used', verbose_name='Maximum Uses'),
        ),
        migrations.AlterField(
            model_name='inviteeventlink',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this link has been used', verbose_name='Used Count'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='events_even_user_id_73ae47_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'is_public'], name='events_even_user_id_5044d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteeventlink',
            index=models.Index(fields=['event', 'expires_at'], name='events_invi_event_i_356149_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteeventlink',
            index=models.Index(fields=['invite_token'], name='events_invi_invite__321880_idx'),
        ),
        migrations.AddIndex(
            model_name='inviteeventlink',
            index=models.Index(fields=['expires_at', 'used_count'], name='events_invi_expires_1d15fc_idx'),
        ),
    ]
