# Generated by Claude for Event.user legacy field removal

from django.conf import settings
from django.db import migrations


def backfill_owner_participants(apps, schema_editor):
    """
    Ensure every Event has an OWNER EventParticipant before we drop Event.user.

    For any Event that still carries Event.user_id but has no matching
    EventParticipant with role='OWNER', create one. Idempotent via get_or_create.
    """
    Event = apps.get_model('events', 'Event')
    EventParticipant = apps.get_model('events', 'EventParticipant')

    events = Event.objects.filter(user_id__isnull=False).values('id', 'user_id').iterator()

    created = 0
    for row in events:
        event_id = row['id']
        user_id = row['user_id']
        has_owner = EventParticipant.objects.filter(event_id=event_id, role='OWNER').exists()
        if has_owner:
            continue

        _, was_created = EventParticipant.objects.get_or_create(
            event_id=event_id,
            user_id=user_id,
            defaults={
                'role': 'OWNER',
                'rsvp_status': 'accepted',
                'join_method': 'direct',
            },
        )
        if was_created:
            created += 1

    if created:
        print(f'[events.0007] Backfilled {created} OWNER participant(s).')


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_alter_inviteeventlink_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_owner_participants, noop_reverse),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_user_id_73ae47_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_user_id_5044d2_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
