# Generated by Django 5.0.4 on 2024-11-18 20:32

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_alter_event_event_gallery_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_gallery_url',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
