# Generated by Claude for the single-OWNER-per-event invariant.
#
# Pre-deploy check (run on production DB before applying):
#
#   SELECT event_id, COUNT(*)
#   FROM events_eventparticipant
#   WHERE role = 'OWNER'
#   GROUP BY event_id
#   HAVING COUNT(*) > 1;
#
# If the query returns rows, resolve duplicates first (demote extras to MODERATOR
# or remove). Otherwise the AddConstraint step will fail when applied.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_remove_event_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(role='OWNER'),
                fields=['event'],
                name='uniq_event_owner',
            ),
        ),
    ]
