# Generated by Django 5.0.4 on 2025-06-22 10:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_event_event_uuid_alter_event_event_gallery_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'event_name'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['name'], 'verbose_name': 'Гість', 'verbose_name_plural': 'Гості'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(
                default=False, help_text='Чи є подія публічною для перегляду', verbose_name='Публічна подія'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='max_guests',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Максимальна кількість гостей (залиште порожнім для необмеженої кількості)',
                null=True,
                verbose_name='Максимальна кількість гостей',
            ),
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Дата та час відправки запрошення',
                null=True,
                verbose_name='Запрошення відправлено',
            ),
        ),
        migrations.AddField(
            model_name='guest',
            name='responded_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Дата та час отримання відповіді від гостя',
                null=True,
                verbose_name='Дата відповіді',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True, help_text='Дата проведення події', verbose_name='Дата події'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(
                help_text='Додайте опис події (не більше 1000 символів)', max_length=1000, verbose_name='Опис'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_gallery_url',
            field=models.CharField(
                db_index=True, editable=False, max_length=10, unique=True, verbose_name='URL галереї'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(
                db_index=True,
                help_text='Введіть назву події (не більше 255 символів)',
                max_length=255,
                verbose_name='Назва події',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID події'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(
                help_text='Власник події',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_events',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Користувач',
            ),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dietary_preferences',
            field=models.TextField(
                blank=True, help_text='Особливі дієтичні переваги або обмеження', verbose_name='Дієтичні переваги'
            ),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(
                db_index=True, help_text='Електронна пошта гостя', max_length=254, verbose_name='Email'
            ),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(
                help_text='Подія, до якої належить гість',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='guests',
                to='events.event',
                verbose_name='Подія',
            ),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(db_index=True, help_text="Ім'я гостя", max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(
                blank=True,
                help_text='Номер телефону у форматі +XXXXXXXXXX',
                max_length=15,
                verbose_name='Номер телефону',
            ),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.CharField(
                choices=[
                    ('accepted', 'Підтверджено'),
                    ('declined', 'Відмовлено'),
                    ('pending', 'Очікується'),
                    ('tentative', 'Можливо'),
                    ('canceled', 'Скасовано'),
                    ('no_show', "Не з'явився"),
                    ('waitlisted', 'У списку очікування'),
                    ('maybe', 'Можливо'),
                    ('confirmed_plus_one', 'Підтверджено +1'),
                    ('declined_with_regret', 'Відмовлено з жалем'),
                ],
                db_index=True,
                default='pending',
                help_text='Статус відповіді на запрошення',
                max_length=20,
                verbose_name='Статус RSVP',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('event', 'email')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='events_even_user_id_73ae47_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'is_public'], name='events_even_date_b3456b_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'rsvp_status'], name='events_gues_event_i_5eb88f_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'email'], name='events_gues_event_i_3e35b7_idx'),
        ),
    ]
