# Generated by Django 5.0.4 on 2025-09-26 12:04

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0008_alter_event_options_alter_guest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gdrive_access_token_encrypted',
            field=models.TextField(
                blank=True,
                help_text='Зашифрований OAuth токен для доступу до Google Drive',
                null=True,
                verbose_name='Encrypted Google Drive Access Token',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='gdrive_folder_id',
            field=models.CharField(
                blank=True,
                help_text='ID папки в Google Drive для зберігання файлів події',
                max_length=255,
                null=True,
                verbose_name='Google Drive Folder ID',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='storage_provider',
            field=models.CharField(
                choices=[('s3', 'Amazon S3'), ('google_drive', 'Google Drive')],
                db_index=True,
                default='s3',
                help_text='Провайдер для зберігання файлів події',
                max_length=20,
                verbose_name='Storage Provider',
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['storage_provider', 'user'], name='events_even_storage_f20da9_idx'),
        ),
    ]
