# Generated by Django 5.0.4 on 2025-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0009_event_gdrive_access_token_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gdrive_access_token_encrypted',
        ),
    ]
