# Generated by Django 5.0.4 on 2025-09-30 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_remove_event_gdrive_access_token_encrypted'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_storage_f20da9_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gdrive_folder_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='storage_provider',
        ),
    ]
