# Generated by Django 5.0.4 on 2025-10-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0011_remove_event_events_even_storage_f20da9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='Користувач-гість (якщо зареєстрований)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='guest_invitations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Користувач',
            ),
        ),
    ]
