# Generated by Django 5.0.4 on 2025-10-08 10:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0013_remove_eventinvite_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Додайте опис події (не більше 1000 символів)',
                max_length=1000,
                verbose_name='Опис',
            ),
        ),
    ]
