# Generated by Django 5.0.4 on 2025-10-13 22:12

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0015_remove_guest_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                (
                    'slug',
                    models.SlugField(help_text='Автоматично генерується з назви', unique=True, verbose_name='URL slug'),
                ),
                (
                    'icon',
                    models.CharField(
                        blank=True, help_text='CSS клас іконки або emoji', max_length=50, verbose_name='Іконка'
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        default='#007bff', help_text='Hex колір для категорії', max_length=7, verbose_name='Колір'
                    ),
                ),
                ('description', models.TextField(blank=True, help_text='Короткий опис категорії', verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Категорія події',
                'verbose_name_plural': 'Категорії подій',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, help_text='Повна адреса проведення події', verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Подія триває весь день', verbose_name='Весь день'),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinates',
            field=models.JSONField(
                blank=True,
                help_text='Координати місця проведення {lat: 50.4501, lng: 30.5234}',
                null=True,
                verbose_name='Координати',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(
                blank=True, help_text='Час закінчення події (опціонально)', null=True, verbose_name='Час закінчення'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(
                choices=[('physical', 'Фізичне місце'), ('online', 'Онлайн подія'), ('hybrid', 'Змішаний формат')],
                default='physical',
                help_text='Фізична, онлайн або змішана подія',
                max_length=20,
                verbose_name='Тип події',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='online_link',
            field=models.URLField(
                blank=True, help_text='Zoom, Meet, Teams або інше посилання', verbose_name='Посилання на онлайн'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(
                blank=True, db_index=True, help_text='Точний час початку події', null=True, verbose_name='Час початку'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(
                choices=[
                    ('Europe/Kiev', 'Київ (UTC+2/+3)'),
                    ('Europe/Warsaw', 'Варшава (UTC+1/+2)'),
                    ('Europe/Berlin', 'Берлін (UTC+1/+2)'),
                    ('Europe/Moscow', 'Москва (UTC+3)'),
                    ('Europe/London', 'Лондон (UTC+0/+1)'),
                    ('US/Eastern', 'Східний час США (UTC-5/-4)'),
                    ('US/Pacific', 'Тихоокеанський час США (UTC-8/-7)'),
                    ('UTC', 'UTC'),
                ],
                default='Europe/Kiev',
                help_text='Часовий пояс події',
                max_length=50,
                verbose_name='Часовий пояс',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(
                blank=True, help_text='Назва залу, ресторану, парку тощо', max_length=255, verbose_name='Назва місця'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Категорія події',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='events.eventcategory',
                verbose_name='Категорія',
            ),
        ),
    ]
