# Generated by Django 5.0.4 on 2025-10-14 11:39

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0017_event_public_id_event_s3_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_uuid',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text='Унікальний ідентифікатор події',
                unique=True,
                verbose_name='UUID події',
            ),
        ),
    ]
