# Generated by Django 5.0.4 on 2025-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0018_alter_event_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_gallery_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='public_id',
        ),
    ]
