# Generated by Django 5.0.4 on 2025-09-26 12:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token_encrypted',
            field=models.TextField(
                blank=True,
                help_text='Зашифрований Google OAuth access token для доступу до Drive користувача',
                null=True,
                verbose_name='Encrypted Google Access Token',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_connected',
            field=models.BooleanField(
                default=False,
                help_text='Чи підключений користувач до Google Drive',
                verbose_name='Google Drive Connected',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token_encrypted',
            field=models.TextField(
                blank=True,
                help_text='Зашифрований Google OAuth refresh token для оновлення доступу',
                null=True,
                verbose_name='Encrypted Google Refresh Token',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token_expires_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Час закінчення дії Google access token',
                null=True,
                verbose_name='Google Token Expires At',
            ),
        ),
    ]
