# Generated by Django 5.0.4 on 2025-12-07 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_remove_clerk_integration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[],
        ),
    ]
