# Generated by Django 5.0.4 on 2026-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_login_method',
            field=models.CharField(choices=[('password', 'Password'), ('passwordless', 'Passwordless')], db_index=True, default='passwordless', help_text='User-selected preferred sign-in method (hint for the client UI)', max_length=16, verbose_name='Preferred Login Method'),
        ),
    ]
