# Generated by Django 5.0.4 on 2025-10-02 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_remove_google_drive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Clerk user identifier for authentication',
                max_length=255,
                null=True,
                unique=True,
                verbose_name='Clerk ID',
            ),
        ),
    ]
