# Generated by Django 5.0.4 on 2025-10-03 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_add_eventinvite_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventinvite',
            new_name='accounts_ev_event_i_b24bd8_idx',
            old_name='accounts_ev_event_i_a88cce_idx',
        ),
        migrations.RenameIndex(
            model_name='eventinvite',
            new_name='accounts_ev_invite__3fe3f8_idx',
            old_name='accounts_ev_invite__fe3e92_idx',
        ),
        migrations.RenameIndex(
            model_name='eventinvite',
            new_name='accounts_ev_expires_13c6b5_idx',
            old_name='accounts_ev_expires_e7e4cb_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='guest_name',
            field=models.CharField(
                blank=True, help_text="Ім'я для анонімних гостей", max_length=255, null=True, verbose_name="Ім'я гостя"
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_token_used',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Токен запрошення, через який було створено анонімного користувача',
                max_length=64,
                null=True,
                verbose_name='Використаний токен запрошення',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous_guest',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Позначає, що це анонімний користувач, створений через QR-код запрошення',
                verbose_name='Анонімний гість',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='original_user',
            field=models.ForeignKey(
                blank=True,
                help_text='Посилання на основний акаунт, якщо анонімний гість пізніше зареєструвався',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='anonymous_guests',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Оригінальний користувач',
            ),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
