# Generated by Django 5.0.4 on 2025-10-13 15:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_migrate_guest_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guest',
            new_name='accounts_gu_event_i_497d39_idx',
            old_name='accounts_gu_event_i_c5b51b_idx',
        ),
        migrations.RenameIndex(
            model_name='guest',
            new_name='accounts_gu_event_i_8a7140_idx',
            old_name='accounts_gu_event_i_3d1ff1_idx',
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
