# Generated by Django 5.0.4 on 2025-10-14 14:02

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_rename_accounts_gu_event_i_c5b51b_idx_accounts_gu_event_i_497d39_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text='External UUID for S3 and API operations',
                null=True,
                verbose_name='User UUID',
            ),
        ),
    ]
