# Generated by Django 5.0.4 on 2025-10-14 14:04

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0013_fix_duplicate_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text='External UUID for S3 and API operations',
                unique=True,
                verbose_name='User UUID',
            ),
        ),
    ]
