# Generated by Django 5.0.4 on 2025-11-03 16:55

import uuid

import django.utils.timezone
from django.db import migrations
from django.db import models

import apps.accounts.managers


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0014_make_user_uuid_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='original_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        db_collation='case_insensitive',
                        help_text='Required for registered users, optional for guests',
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name='email address',
                    ),
                ),
                (
                    'is_registered',
                    models.BooleanField(
                        db_index=True, default=False, help_text='True for registered users, False for guests'
                    ),
                ),
                (
                    'user_uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='UUID for S3 storage structure and external references',
                        unique=True,
                        verbose_name='User UUID',
                    ),
                ),
                (
                    'clerk_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Clerk user identifier for authentication',
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name='Clerk ID',
                    ),
                ),
                (
                    'guest_name',
                    models.CharField(
                        blank=True,
                        help_text='Display name for guest users in events',
                        max_length=255,
                        verbose_name='Guest Display Name',
                    ),
                ),
                (
                    'invite_token_used',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Token used to create this guest user',
                        max_length=64,
                        null=True,
                        verbose_name='Used Invitation Token',
                    ),
                ),
                (
                    'original_guest_data',
                    models.JSONField(
                        blank=True,
                        help_text='Backup of guest data when user registers',
                        null=True,
                        verbose_name='Original Guest Data',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_customuser',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='EventInvite',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_registered'], name='accounts_cu_email_faf1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_registered', 'is_active'], name='accounts_cu_is_regi_3545d4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_uuid'], name='accounts_cu_user_uu_90ec91_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['clerk_id'], name='accounts_cu_clerk_i_72e6de_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['invite_token_used'], name='accounts_cu_invite__8ed325_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(
                check=models.Q(('is_registered', False), ('email__isnull', False), _connector='OR'),
                name='registered_users_must_have_email',
            ),
        ),
    ]
