# Generated by Django 5.0.4 on 2025-11-04 15:38

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Введіть назву альбому (не більше 255 символів)',
                        max_length=255,
                        verbose_name='Назва альбому',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Додайте опис альбому (не більше 500 символів)',
                        max_length=500,
                        verbose_name='Опис альбому',
                    ),
                ),
                (
                    'album_uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID альбому'
                    ),
                ),
                (
                    'album_s3_prefix',
                    models.CharField(
                        help_text='S3 шлях для зберігання файлів альбому',
                        max_length=500,
                        unique=True,
                        verbose_name='S3 Prefix',
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        default=False, help_text='Чи є альбом публічним для перегляду', verbose_name='Публічний альбом'
                    ),
                ),
                (
                    'cover_image_s3_key',
                    models.CharField(
                        blank=True,
                        help_text='S3 ключ для обкладинки альбому',
                        max_length=500,
                        verbose_name='Обкладинка альбому',
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0, help_text='Порядок відображення альбому в списку', verbose_name='Порядок сортування'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        help_text='Подія, до якої належить альбом',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='albums',
                        to='events.event',
                        verbose_name='Подія',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбоми',
                'ordering': ['sort_order', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'download_uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID завантаження'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Очікується'),
                            ('processing', 'Обробляється'),
                            ('completed', 'Завершено'),
                            ('failed', 'Помилка'),
                            ('expired', 'Минув термін дії'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Поточний статус завантаження',
                        max_length=20,
                        verbose_name='Статус завантаження',
                    ),
                ),
                (
                    'download_url',
                    models.URLField(
                        blank=True,
                        help_text='Тимчасове посилання для завантаження',
                        max_length=500,
                        null=True,
                        verbose_name='URL завантаження',
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='Дата та час закінчення дії посилання',
                        null=True,
                        verbose_name='Дата закінчення',
                    ),
                ),
                (
                    'file_count',
                    models.PositiveIntegerField(
                        default=0, help_text='Кількість файлів в архіві', verbose_name='Кількість файлів'
                    ),
                ),
                (
                    'archive_size',
                    models.BigIntegerField(
                        blank=True,
                        help_text='Розмір створеного архіву в байтах',
                        null=True,
                        verbose_name='Розмір архіву',
                    ),
                ),
                (
                    'error_message',
                    models.TextField(
                        blank=True,
                        help_text='Деталі помилки якщо завантаження невдале',
                        verbose_name='Повідомлення про помилку',
                    ),
                ),
                (
                    'album',
                    models.ForeignKey(
                        help_text='Альбом для завантаження',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='downloads',
                        to='albums.album',
                        verbose_name='Альбом',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Завантаження',
                'verbose_name_plural': 'Завантаження',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['event', 'created_at'], name='albums_albu_event_i_31f78f_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['event', 'is_public'], name='albums_albu_event_i_b43366_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['event', 'sort_order'], name='albums_albu_event_i_aa978e_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['album_uuid'], name='albums_albu_album_u_e33d20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('event', 'name')},
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['album', 'status'], name='albums_down_album_i_57ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['status', 'expires_at'], name='albums_down_status_a9b8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['download_uuid'], name='albums_down_downloa_7de443_idx'),
        ),
    ]
