# Generated by Django 5.0.4 on 2024-06-09 07:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
        ('events', '0002_event_attendees_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='events.event'
            ),
        ),
    ]
