# Generated by Django 5.0.4 on 2026-02-24 21:46

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
        ('events', '0006_alter_inviteeventlink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={
                'ordering': ['sort_order', '-created_at', 'name'],
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбоми',
            },
        ),
        migrations.AlterModelOptions(
            name='download',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Завантаження',
                'verbose_name_plural': 'Завантаження',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='album_s3_prefix',
            field=models.CharField(
                help_text='S3 шлях для зберігання файлів альбому', max_length=500, unique=True, verbose_name='S3 Prefix'
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image_s3_key',
            field=models.CharField(
                blank=True,
                help_text='S3 ключ для обкладинки альбому',
                max_length=500,
                verbose_name='Обкладинка альбому',
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Додайте опис альбому (не більше 500 символів)',
                max_length=500,
                verbose_name='Опис альбому',
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='event',
            field=models.ForeignKey(
                help_text='Подія, до якої належить альбом',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='albums',
                to='events.event',
                verbose_name='Подія',
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(
                default=False, help_text='Чи є альбом публічним для перегляду', verbose_name='Публічний альбом'
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(
                db_index=True,
                help_text='Введіть назву альбому (не більше 255 символів)',
                max_length=255,
                verbose_name='Назва альбому',
            ),
        ),
        migrations.AlterField(
            model_name='album',
            name='sort_order',
            field=models.PositiveIntegerField(
                default=0, help_text='Порядок відображення альбому в списку', verbose_name='Порядок сортування'
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='album',
            field=models.ForeignKey(
                help_text='Альбом для завантаження',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='downloads',
                to='albums.album',
                verbose_name='Альбом',
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='archive_size',
            field=models.BigIntegerField(
                blank=True, help_text='Розмір створеного архіву в байтах', null=True, verbose_name='Розмір архіву'
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='download_url',
            field=models.URLField(
                blank=True,
                help_text='Тимчасове посилання для завантаження',
                max_length=500,
                null=True,
                verbose_name='URL завантаження',
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='download_uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID завантаження'
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='error_message',
            field=models.TextField(
                blank=True,
                help_text='Деталі помилки якщо завантаження невдале',
                verbose_name='Повідомлення про помилку',
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='Дата та час закінчення дії посилання',
                null=True,
                verbose_name='Дата закінчення',
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='file_count',
            field=models.PositiveIntegerField(
                default=0, help_text='Кількість файлів в архіві', verbose_name='Кількість файлів'
            ),
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Очікується'),
                    ('processing', 'Обробляється'),
                    ('completed', 'Завершено'),
                    ('failed', 'Помилка'),
                    ('expired', 'Минув термін дії'),
                ],
                db_index=True,
                default='pending',
                help_text='Поточний статус завантаження',
                max_length=20,
                verbose_name='Статус завантаження',
            ),
        ),
    ]
