# Generated by Django 5.0.4 on 2024-07-08 15:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0002_alter_album_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_prefix',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
