# Generated by Django 5.0.4 on 2024-11-25 16:55

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0003_album_album_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_prefix',
        ),
        migrations.AddField(
            model_name='album',
            name='album_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
