# Generated by Django 5.0.4 on 2024-11-25 18:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0004_remove_album_album_prefix_album_album_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_s3_prefix',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
