# Generated by Django 5.0.4 on 2025-05-05 11:50

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0005_album_album_s3_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('download_url', models.URLField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='albums.album'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
