# Generated by Django 5.0.4 on 2025-11-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mediafilePK', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=255)),
                ('S3_bucket_name', models.CharField(max_length=255)),
                ('S3_object_key', models.CharField(max_length=255)),
                (
                    'album_id',
                    models.ForeignKey(
                        db_column='album_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mediafiles',
                        to='albums.album',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        db_column='user_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mediafiles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='downloads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'mediafile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='downloads',
                        to='mediafiles.mediafile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
