# Generated by Django 5.0.4 on 2026-03-19 09:21

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='S3_object_key',
            field=models.CharField(max_length=500),
        ),
    ]
