# Generated by Django 5.0.4 on 2024-06-09 07:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(default=12, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
