# Generated by Django 5.0.4 on 2024-06-09 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mediafiles', '0002_mediafile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file',
        ),
    ]
