# Generated by Django 5.0.4 on 2025-06-22 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0006_download'),
        ('mediafiles', '0004_rename_user_pk_to_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='album_pk',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='album_id',
            field=models.ForeignKey(
                db_column='album_id',
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mediafiles',
                to='albums.album',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='user_id',
            field=models.ForeignKey(
                db_column='user_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mediafiles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
